#!/bin/bash
#
# Copyright (c) 2013-2021 Igor Pecovnik, igor.pecovnik@gma**.com
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.

# DO NOT EDIT THIS FILE
# use configuration files like config-default.conf to set the build configuration
# Please check Orange Pi documentation for more info
#  http://www.orangepi.cn/downloadresourcescn
#  http://www.orangepi.org/downloadresources

SRC="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
EXTER="${SRC}/external"

cd "${SRC}" || exit

source "${SRC}"/scripts/general.sh

prepare_host_basic

CONFIG="userpatches/config-default.conf"
CONFIG_FILE="$(realpath "${CONFIG}")"
CONFIG_PATH=$(dirname "${CONFIG_FILE}")

source "${SRC}"/scripts/extensions.sh

display_alert "Using config file" "${CONFIG_FILE}" "info"
pushd "${CONFIG_PATH}" > /dev/null || exit

source "${CONFIG_FILE}"
popd > /dev/null || exit

USERPATCHES_PATH="${CONFIG_PATH}"

source "${SRC}"/scripts/main.sh
